# This is a basic workflow to help you get started with Actions

name: Build-exe

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  watch:
    type: started

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        toolset: [MSVC]
        configuration: [Release]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: danielkrupinski/Osiris
        path: Osiris  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Set toolset
      if: matrix.toolset == 'ClangCL'
      run: echo "toolset=/p:PlatformToolset=${{ matrix.toolset }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Build Osiris.dll
      shell: cmd
      run: msbuild D:\a\cs2-injector\cs2-injector\Osiris\Osiris.sln /p:Platform=x64 /p:Configuration=${{ matrix.configuration }} ${{ env.toolset }} /p:OutDir=D:\a\cs2-injector\cs2-injector\Osiris\output\
    - name: show build result
      shell: cmd
      run: dir D:\a\cs2-injector\cs2-injector\Osiris\output\
    - name: build inject.exe
      shell: cmd
      run: msbuild Manual Map Injector.sln /p:Platform=x64 /p:Configuration=Release ${{ env.toolset }} 
    - name: Commit  files
      run: |
        cd D:\a\cs2-injector\cs2-injector\Osiris\output\
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name whispin
        git add .
        git commit -m "update exe" -a  
    - name: Push  file
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: .\
